<h1><?=$title?></h1>

<form action='articleApply.php' method='POST' enctype="multipart/form-data">
    <input class="d-none" 
        type="text" 
        name="id"
        placeholder="ID" 
        value='<?=$article['id']?>'/>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Titre</p>
        <input class="form-control col-sm-10" type="text" name="title" placeholder="Titre" value='<?=$article['title']?>' required/>
    </div>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Date de publication</p>
        <div class="form-inline col-sm-10">
            <input type="date" name="date">
            <input type="time" name="time">
            &nbsp;Laisser vide pour publier tout de suite.
        </div>
    </div>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Catégorie</p>
        <select class="col-sm-10 custom-select" name="category" required>
            <option value=''>Choisissez une catégorie</option>
            <?php foreach($categories as $category): ?>
                <option value='<?=$category['id']?>' <?=$category['id'] == $article['category']?'selected':null?>><?=$category['title']?></option>;
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Image</p>
        <?php if(isset($article['picture'])): ?>
            <div class="col-sm-2">
                <img class='img-fluid' src='<?= '../../img/uploads/articles/'.$article['picture']?>' alt=''/>
                <p>Image actuelle</p>
            </div>
        <?php endif; ?>
        <div class="col">
            <input 
                type="file" 
                name="picture" 
                value='<?= $article['picture']?>'
            />
            <br>
            <?php if (isset($article['picture'])): ?>
                <input 
                    type="checkbox" 
                    name="delete_picture" 
                    id="picture"
                >
                <label for="picture">Supprimer image</label>
            <?php endif ; ?>
        </div>
        
    </div>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Contenu</p>
            <textarea required class="form-control col-sm-10" textarea name="content" name="content" cols="30" rows="10" placeholder="Contenu"><?=$article['content']?></textarea>
    </div>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Posté par</p>
        <select class="col-sm-10 custom-select" name="author">
            <option value=''>Choisissez un utilisateur</option>
            <?php foreach($users as $user): ?>
              <option value='<?=$user['id']?>' <?= $_SESSION['userId'] == $user['id']?'selected':null?>><?=$user['firstname']?></option>
            <?php endforeach; ?>              
        </select>
    </div>
    
    <button type="submit" class="btn btn-primary"><?=$action?></button>
</form>

