<h1><?=$title?></h1>

<form action='categoryApply.php' method='POST'>
    <input class="d-none" 
        type="text" 
        name="id"
        placeholder="ID" 
        value='<?=$category['id']?>'/>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Nom</p>
        <input 
            class="form-control col-sm-10" 
            type="text" 
            name="title" 
            placeholder="Nom" 
            value='<?=$category['title']?>'/>
    </div>

    <div class="form-group row">
        <p class="col-sm-2 col-form-label">Catégorie parent</p>
        <select 
            class="col-sm-10 custom-select" 
            name="parent"
        >
            <option value=''>Aucune</option>
            <?php foreach($categories as $parent): ?>
                <option 
                    value='<?=$parent['id']?>' 
                    <?= $parent['id'] == $category['parent'] ? 'selected':null?> 
                ><?=$parent['title']?></option>
            <?php endforeach ;?>
        </select>
    </div>


    <button type="submit" class="btn btn-primary"><?=$action?></button>
</form>

