<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Blo</title>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/style.css" type="text/css" />
</head>
<body>
    <header>
      Blo
    </header>
    <main>
      <div class="container bg-secondary">
        <h1>Login</h1>
        
        <?php if(isset($_SESSION['flashbag'])):?>
          <div class="col-3 alert alert-danger">
            <strong><?=$_SESSION['flashbag']?></strong>
          </div>
        <?php endif; ?>
        
        <form method="POST" action="connect.php">
          Email
          <input 
            type="email" 
            name="email"
            class="form-control col-sm-2"
          />
            Mot de passe
          <input 
            type="password"
            name="password"
            class="form-control col-sm-2"
          />
          <input type="submit" value="Submit"/>
        </form>
      </div>
    </main>
    <footer>
        
    </footer>
</body>
</html>