<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blo</title>
</head>
<body>
    <header>
        <nav>
            <a href="#">Auto</a>
            <a href="#">Moto</a>
            <a href="#">Mode</a>
            <a href="#">Cuisine</a>
        </nav>
    </header>
    <main>
        <div class="container">
            <h1>BLOG</h1>
            
            <article>
                <div><h2>titre</h2> - <span>Catégorie (grisé)</span></div>
                <div><user>Utilisateur</user> le date<div>
            </article>
            
        </div>
    </main>
    <footer></footer>
</body>
</html>